# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0005_auto_20170111_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homem',
            old_name='company1',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='homem',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='homem',
            old_name='testimonial1',
            new_name='testimonial',
        ),
        migrations.RenameField(
            model_name='mid',
            old_name='mimg',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='mid',
            old_name='num1',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='mid',
            old_name='num2',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='midlo',
            old_name='im1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='midlo',
            old_name='say1',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='recentworks',
            old_name='cmpny1',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='recentworks',
            old_name='rw1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recentworks',
            old_name='cmpny2',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='bottomlogos',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='bottomlogos',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='bottomlogos',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='bottomlogos',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='bottomlogos',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='bottomlogos',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='desc2',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='desc3',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='slider1',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='slider3',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='homesliderimages1',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='mid',
            name='num3',
        ),
        migrations.RemoveField(
            model_name='mid',
            name='num4',
        ),
        migrations.RemoveField(
            model_name='mid',
            name='wri1',
        ),
        migrations.RemoveField(
            model_name='mid',
            name='wri2',
        ),
        migrations.RemoveField(
            model_name='mid',
            name='wri3',
        ),
        migrations.RemoveField(
            model_name='mid',
            name='wri4',
        ),
        migrations.RemoveField(
            model_name='midlo',
            name='im2',
        ),
        migrations.RemoveField(
            model_name='midlo',
            name='im3',
        ),
        migrations.RemoveField(
            model_name='midlo',
            name='im4',
        ),
        migrations.RemoveField(
            model_name='midlo',
            name='say2',
        ),
        migrations.RemoveField(
            model_name='midlo',
            name='say3',
        ),
        migrations.RemoveField(
            model_name='midlo',
            name='say4',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='cmpny3',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='cmpny4',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='rw2',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='rw3',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='rw4',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='website1',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='website2',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='website3',
        ),
        migrations.RemoveField(
            model_name='recentworks',
            name='website4',
        ),
        migrations.RemoveField(
            model_name='text1',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='text2',
            name='desc',
        ),
        migrations.AddField(
            model_name='bottomlogos',
            name='logo',
            field=models.ImageField(null=True, upload_to=b'logos'),
        ),
        migrations.AddField(
            model_name='homesliderimages1',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name=b'description', blank=True),
        ),
        migrations.AddField(
            model_name='homesliderimages1',
            name='image',
            field=models.ImageField(null=True, upload_to=b'images'),
        ),
        migrations.AddField(
            model_name='homesliderimages1',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name=b'title', blank=True),
        ),
        migrations.AddField(
            model_name='text1',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name=b'description', blank=True),
        ),
        migrations.AddField(
            model_name='text2',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name=b'description', blank=True),
        ),
        migrations.AlterField(
            model_name='text1',
            name='boldtitle',
            field=models.CharField(max_length=255, null=True, verbose_name=b'boldtitle', blank=True),
        ),
        migrations.AlterField(
            model_name='text1',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name=b'text', blank=True),
        ),
        migrations.AlterField(
            model_name='text2',
            name='boldtitle',
            field=models.CharField(max_length=255, null=True, verbose_name=b'boldtitle', blank=True),
        ),
        migrations.AlterField(
            model_name='text2',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name=b'text', blank=True),
        ),
    ]
